Faster primesieve::iterator (#53)
* Try implementing next_prime()

* Fix bugs

* Revert to old code

* Refactor

* Rename SieveOfEratosthenes to Erat

* Rename Erat to sieve

* Use init() instead of constructors

* Rename ParallelPrimeSieve to ParallelSieve

* Refactor

* Fix SievingPrimes bug

if (low_ < stop_) cannot be used to reliably test if there are still segments left that need to be sieved

* Rename next_prime() to nextPrime()

* Refactor

* Remove unused variable

* Refactor

* Refactor

* Get rid of NUMBERS_PER_BYTE

* Enable testing

* Silence compiler warning

error: ‘primesieve::Erat::maxPreSieve_’ will be initialized after ‘primesieve::Erat::sieve_‘

* Refactor

* Rename initWheel() to Wheel::init()

* Move PreSieve into PrimeGenerator

* include <algorithm>

* Use const correctness

* Make most methods protected

* Refactor

* Improve numberOfBits()

* Improve numberOfBits()

* Add numberOfBits() test

* Add NextPrime class

* Fix small primes < 7

* Fix clang warning

NextPrime.cpp:41:4: error: suggest
      braces around initialization of subobject [-Werror,-Wmissing-braces]
   0,  0,  1,  2,  2,  3,  3,  4,  4,  4,

* Refactor

* Lazy initialize PreSieve

* Refactor

* Add array size

* More cache efficient lookup table

* Refactor

* Refactor

* Use get_sieve_size()

* Faster primesieve::iterator

* Fix delete pointer

* Fix small primes

* Rename NextPrime to NextPrimes

* primesieve::iterator API changed

primesieve::iterator now returns UINT64_MAX if prime > 2^64 instead of throwing an error.

* Fix use of uninitialized value

* Improve max prime gap < 10

* Refactor

* Add NextPrimes.cpp

* Speed up small ranges

* Refactor

* Add constructors to Erat

* Update comment

* Add maxCachedPrime()

* Do not inline constructor

* Reorder member variables

* Add IteratorHelper class

* Make it work

* Refactor

* Refactor

* Update memory usage

* Refactor

* Add IteratorHelper.cpp

* Refactor

* Remove unnecessary if

* Update documentation

* Add NextPrimes::finished()

* Simplify error handling

* Update documentation

* Refactor

* Fix Linux performance regression

allocating primes_[64] on the stack (512 bytes) causes lots of brk system calls into the Linux kernel which slows down sieving tiny ranges by up to 2x.

* Fix Linux performance regression (2nd attempt)

Run: strace test/S2_easy_xy
There should be no brk system calls.

* Do not lazy initialize PreSieve

On Linux this causes serious performance regression.

* Do not inline destructor

Reduces code bloat

* Silence MSVC compiler warning

iteratorhelper.cpp(52): warning C4244: '=': conversion from 'uint64_t' to 'double', possible loss of data

* Store primes using primesieve::iterator

* Remove unused methods

* Rename primes_helper() to store_primes()

* Update documentation

* Rename PrimeGenerator to PrintPrimes

* Update documentation

* Silence MSVC compiler warnings

storeprimes.hpp(41): warning C4244: 'argument': conversion from 'uint64_t' to 'const short', possible loss of data

* Update version to 7.0

* Update documentation

* Update README.md

* Changes in version 7.0

* Generate primes > start