Fix undefined reference to `__atomic_fetch_add_8' (#46)
* Find libatomic

* Improve libatomic detection

* Use -std=c++11  to compile <atomic>

* Refactor libatomic detection

* Changes in version 6.3

* Use CMAKE_REQUIRED_FLAGS instead of CMAKE_REQUIRED_DEFINITIONS